
export const AuctionStatus: any = {
	DRAFT: 2,
	SOON: 7,
	ONGOING: 1,
	FINISHED: 3,
	ARCHIVED: 4,
	SOLD: 5,
	UNSOLD: 6,
}

export interface Auction {
	active_id: number,
	appraisal_value: number,
	auction_status_id: number,
	auction_type_id: number,
	asset: string,
	bid_list: Array<Bid>,
	bid_price_interval: number,
	bid_time_interval: number,
	bids: number,
	commission: number,
	complete_deposits: number,
	conditions: string,
	conditions_document: any,
	conditions_archive: any,
	created_at: string,
	deposit: number,
	description: string,
	description_document: any,
	description_archive: any,
	end_date: string,
	end_time: string,
	favorites: number,
	featured: boolean,
	dontshowtimer: boolean,
	id: number,
	images: any,
	land_registry: string,
	land_registry_document: any,
	land_registry_archive: any,
	last_bid: number,
	max_bid: number,
	minimum_bid: number,
	notifications: Array<Notification>,
	order: number,
	public_path: string,
	seen: boolean,
	sold_at: string,
	start_date: string,
	start_price: number,
	start_time: string,
	status: string,
	technical_specifications: string,
	technical_document: any,
	technical_archive: any,
	title: string,
	views: number,
	link_rewrite: string,
}

export interface Bid {
	auction_id: number,
	created_at: string,
	id: number,
	price: number,
	seen: boolean,
	type: string,
	user: string,
}

export interface Deposit {
	archive_id: number,
	auction_id: number,
	created_at: string,
	deposit: number,
	document_number: string,
	firstname: string,
	id: number,
	lastname: string,
	receipt_path: string,
	user_id: number,
	username: string,
	valid: boolean,
}

export interface Offer {
	created_at: string,
	id: number,
	price: number,
	user: string,
	user_id: number,
}
