
export interface User {
	address: string,
	bid: number,
	birthdate: string,
	city: string,
	confirmed: boolean,
	country: string,
	country_id: number,
	cp: string,
	created_at: string,
	document_number: string,
	document: any,
	email: string,
	firstname: string,
	id: number,
	is_best_bid: boolean,
	lastname: string,
	notification_auctions: boolean,
	notification_favorites: boolean,
	notification_news: boolean,
	number_bids: number,
	number_login: number,
	offer: number,
	phone: string,
	province: string,
	province_id: number,
	role: string,
	role_id: number,
	seen: boolean,
	status: number,
	username: string,
	validated: boolean,
}

export interface Representation {
	address: string,
	alias: string,
	city: string,
	country_id: number,
	cp: string,
	created_at: string,
	document_number: string,
	file: any,
	firstname: string,
	id: number,
	lastname: string,
	province_id: number,
	representation_type_id: number,
	status: number,
	type: string,
	use_user_address: boolean,
	user_id: number,
}

export interface RepresentationType {
	id: number,
	name: string,
}
